
OPACITY_DEFAULT = 255
ZOOM_DEFAULT =1.0
ROTATE_DEFAULT = 0
FLIP_OPTIONS = ['None', 'X', 'Y', 'Both']
BLUR_DEFAULT = 0
SHARPNESS_DEFAULT = 0
EFFECT_OPTION = ['None', 'Emboss','Find edges', 'Contour','Edge enchance']
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GRAYSCALE_DEFAULT = False
INVERT_DEFAULT = False
CONTROL_POINTS_DEFAULT = [(0,0 ), (0.3,0.3), (0.7,0.7),(1,1)]


BACKGROUND_COLOR = '#242424'
WHITE = '#FFF'
GREY = 'grey'
BLUE = '#1f6aa5'
DARK_FREY = '#4A4A4A'
CLOSE_RED = '#8A0606'
SLIDER_BG = '#6466B6'

DROPDOWN_MAIN_COLOR = '#444'
DROPDOWN_HOVER_COLOR = '#333'
DROPDOWN_MENU_COLOR = '#666'

DEFAULT_VALLUE = (ROTATE_DEFAULT,FLIP_OPTIONS,BRIGHTNESS_DEFAULT,GRAYSCALE_DEFAULT,INVERT_DEFAULT,VIBRANCE_DEFAULT,BLUR_DEFAULT,SHARPNESS_DEFAULT,EFFECT_OPTION)